/*
 *   This file is part of Foobar.
 *
 *   Foobar is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Foobar is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
package mx.tecabix.view;

import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import mx.tecabix.service.controller.LogController;
/**
 * 
 * @author Ramirez Urrutia Angel Abinadi
 * 
 */
public class ErrorLog extends javax.swing.JDialog {


    public ErrorLog(java.awt.Frame parent, Exception ex) {
        super(parent, true);
        initComponents();
        StringBuilder sb = new StringBuilder(LocalDateTime.now().toString());
        sb.append('\n');
        sb.append(ex.getMessage());
        sb.append('\n');
        sb.append(ex.getCause());
        sb.append('\n');
        sb.append(ex.fillInStackTrace());
        sb.append('\n');
        StackTraceElement[] ste = ex.getStackTrace();
        for (int i = 0; i < ste.length; i++) {
            sb.append(ste[i]);
            sb.append('\n');
        }
        jTextAreaDetalles.setText(sb.toString());
        jTextAreaDetalles.setCaretPosition(0);
        setLocationRelativeTo(parent);
        setVisible(true);
    }
    
    public ErrorLog(JDialog parent, Exception ex) {
        super(parent, true);
        initComponents();
        StringBuilder sb = new StringBuilder(LocalDateTime.now().toString());
        sb.append('\n');
        if(ex.getMessage() != null){
            sb.append(ex.getMessage());
            sb.append('\n');
        }
        if(ex.getCause() != null){
            sb.append(ex.getCause());
            sb.append('\n');
        }
        if(ex.fillInStackTrace() != null){
            Throwable th = ex.fillInStackTrace();
            sb.append(th);
            sb.append('\n');
            
            if(th.getLocalizedMessage() != null){
                sb.append(th.getLocalizedMessage());
                sb.append('\n');
            }
            if(th.getMessage() != null){
                sb.append(th.getLocalizedMessage());
                sb.append('\n');
            }
        }
        
        
        StackTraceElement[] ste = ex.getStackTrace();
        if(ste != null){
            for (int i = 0; i < ste.length; i++) {
                sb.append(ste[i]);
                sb.append('\n');
                sb.append(ste[i].getClassName()).append('\n');
                sb.append(ste[i].getFileName()).append('\n');
                sb.append(ste[i].getMethodName()).append('\n');
                
            }
        }
        
        Throwable[] throwable = ex.getSuppressed();
        if(throwable != null){
            for (int i = 0; i < throwable.length; i++) {
                sb.append(throwable[i]);
                sb.append('\n');
                sb.append(throwable[i].getLocalizedMessage()).append('\n');
                sb.append(throwable[i].getMessage()).append('\n');
            }
        }
        
        jTextAreaDetalles.setText(sb.toString());
        jTextAreaDetalles.setCaretPosition(0);
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalles = new javax.swing.JTextArea();
        jButtonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneComentarios = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/64/advertencia.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Se produjo una excepción.");

        jTextAreaDetalles.setEditable(false);
        jTextAreaDetalles.setColumns(20);
        jTextAreaDetalles.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalles);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Este reporte se enviara a tecabix automáticamente.");

        jLabel4.setText("Comentarios");
        jLabel4.setToolTipText("proporcione todos los pasos necesarios para replicar el problema.");

        jTextPaneComentarios.setToolTipText("proporcione todos los pasos necesarios para replicar el problema.");
        jTextPaneComentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPaneComentariosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPaneComentarios);

        jLabel5.setText("Detalles del problema");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    LogController logController = new LogController();
                    String comentarios = jTextPaneComentarios.getText();
                    String reporte = jTextAreaDetalles.getText();
                    StringBuilder cuerpo = new StringBuilder(comentarios);
                    cuerpo.append("\n\n").append(reporte);
                    logController.post(cuerpo.toString());
                } catch (Exception ex) {
                    Logger.getLogger(ErrorLog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        hilo.start();
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextPaneComentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaneComentariosKeyTyped
        if(jTextPaneComentarios.getText().length() > 500){
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if(caracter == '<' || caracter == '(' || caracter == ';'){
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextPaneComentariosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDetalles;
    private javax.swing.JTextPane jTextPaneComentarios;
    // End of variables declaration//GEN-END:variables
}
